### ISSUE TITLE
[bug]  [1.21.11] 1.14.0 cannot be used

### ISSUE THREAD

**Issue by ReDece** [Siphalor/mouse-wheelie#273]
When I start the game, my launcher tells me: "The current game cannot continue running due to the mod 'mousewheelie' at 'de.siphalor.mousewheelie.MouseWheelie' error."
This is the crash：
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mousewheelie' at 'de.siphalor.mousewheelie.MouseWheelie'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:409)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:475)
	at knot//net.minecraft.client.main.Main.main(Main.java:234)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at knot//de.siphalor.tweed5.fabric.helper.api.FabricConfigCommentLoader.<clinit>(FabricConfigCommentLoader.java:16)
	at knot//de.siphalor.mousewheelie.MouseWheelie.initializeConfig(MouseWheelie.java:101)
	at knot//de.siphalor.mousewheelie.MouseWheelie.onInitialize(MouseWheelie.java:75)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:239)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more`
The module list includes only the following items, aside from the mousewheelie:"fabric-api-0.139.5+1.21.11,cloth-config-21.11.151-fabric"
Hope this helps

**Comment by Siphalor** [comment]
Thanks for reporting, I just pushed out fix version 1.14.1.

**Comment by thimblebird** [comment]
on 1.21.10, it's still crashing for me, reporting the config as the culprit:

```
---- Minecraft Crash Report ----
// This doesn't make any sense!
Time: 2025-12-16 10:07:06
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mousewheelie' at 'de.siphalor.mousewheelie.MouseWheelie'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:409)
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407)
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
at knot//net.minecraft.class_310.<init>(class_310.java:483)
at knot//net.minecraft.client.main.Main.main(Main.java:234)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:514)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at com.modrinth.theseus.MinecraftLaunch.relaunch(MinecraftLaunch.java:63)
at com.modrinth.theseus.MinecraftLaunch.main(MinecraftLaunch.java:28)
Caused by: java.lang.NullPointerException: Cannot read field "sort" because "de.siphalor.mousewheelie.MouseWheelie.config" is null
at knot//de.siphalor.mousewheelie.client.util.CreativeSearchOrder.refreshItemSearchPositionLookup(CreativeSearchOrder.java:57)
at knot//de.siphalor.mousewheelie.client.MWClient.onConfigChanged(MWClient.java:152)
at knot//de.siphalor.mousewheelie.MouseWheelie.loadConfig(MouseWheelie.java:89)
at knot//de.siphalor.mousewheelie.MouseWheelie.onInitialize(MouseWheelie.java:76)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405)
... 10 more
```

so i thought maybe it works when removing (or renaming) the current config. this results in an "empty" config file being generated, only containing "null" and the following error:

```
[10:10:36] [Render thread] [Mod Menu | ModsScreen/ERROR]:
Error from mod 'mousewheelie'
java.lang.IllegalStateException: Failed to map root entry
at knot//de.siphalor.tweed5.coat.bridge.impl.TweedCoatBridgeExtensionImpl.createConfigScreen(TweedCoatBridgeExtensionImpl.java:49)
at knot//de.siphalor.mousewheelie.client.MWClient.createConfigScreen(MWClient.java:265)
at knot//de.siphalor.mousewheelie.client.compat.MWModMenuEntryPoint.lambda$getModConfigScreenFactory$0(MWModMenuEntryPoint.java:27)
at knot//com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:70)
at knot//com.terraformersmc.modmenu.gui.ModsScreen.safelyOpenConfigScreen(ModsScreen.java:637)
at knot//com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.openConfig(ModListEntry.java:197)
at knot//com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25402(ModListEntry.java:186)
at knot//net.minecraft.class_4069.method_25402(class_4069.java:46)
at knot//net.minecraft.class_9017.method_25402(class_9017.java:58)
at knot//net.minecraft.class_4069.method_25402(class_4069.java:46)
at knot//net.minecraft.class_312.mixinextras$bridge$method_25402$61(class_312.java)
at knot//net.minecraft.class_312.wrapOperation$zde000$architectury$wrapMouseClicked(class_312.java:1086)
at knot//net.minecraft.class_312.mixinextras$bridge$wrapOperation$zde000$architectury$wrapMouseClicked$64(class_312.java)
at knot//net.minecraft.class_312.wrapOperation$blf000$fabric-screen-api-v1$invokeMouseClickedEvents(class_312.java:1556)
at knot//net.minecraft.class_312.method_1601(class_312.java:125)
at knot//net.minecraft.class_312.method_22686(class_312.java:247)
at knot//net.minecraft.class_1255.execute(class_1255.java:110)
at knot//net.minecraft.class_312.method_22684(class_312.java:247)
at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
at knot//org.lwjgl.system.JNI.invokeV(Native Method)
at knot//org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
at knot//com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:170)
at knot//net.minecraft.class_310.method_1523(class_310.java:1401)
at knot//net.minecraft.class_310.method_1514(class_310.java:969)
at knot//net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:514)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at com.modrinth.theseus.MinecraftLaunch.relaunch(MinecraftLaunch.java:63)
at com.modrinth.theseus.MinecraftLaunch.main(MinecraftLaunch.java:28)
[10:10:36] [Render thread] [Mod Menu | ModsScreen/ERROR]:
Error from mod 'mousewheelie'
```

**Comment by thimblebird** [comment]
it works now. thank you!
